### ISSUE TITLE
[BUG] AppliedWork wasn't be created again after it be deleted

### ISSUE THREAD

**Issue by mingqishao** [Azure/k8s-work-api#83]
### **Describe the bug**
After create the work in hub side and all manifest successfully be applied in member side, I manually deleted the corresponding AppliedWork from member cluster.  The AppliedWork didn't be created again.

### **Environment**
Please provide the following: 
- Hub cluster details
export HUBSUB=26ad903f-2330-429d-8389-864ac35c4350
export HUBRG=bb-work-standard
export HUBNAME=workhubscene1
az account set --subscription $HUBSUB
az aks get-credentials --resource-group $HUBRG  --name $HUBNAME --admin
kubectl config use-context $HUBCONTEXT

- Member cluster details
export MEMSUB=26ad903f-2330-429d-8389-864ac35c4350
export MEMRG=bb-work-standard
export MEMNAME=workmemberscene1
az account set --subscription $MEMSUB
az aks get-credentials --resource-group $MEMRG  --name $MEMNAME --admin
kubectl config use-context $MEMCONTEXT

- Work resource details
```
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: Work
metadata:
  name: test-work
  namespace: default
spec:
  workload:
    manifests:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: test-nginx
        namespace: default
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: test-nginx
        strategy:
          rollingUpdate:
            maxSurge: 50%
            maxUnavailable: 50%
          type: RollingUpdate
        template:
          metadata:
            creationTimestamp: null
            labels:
              app: test-nginx
          spec:
            containers:
            - image: nginx:1.14.2
              name: nginx
              ports:
              - containerPort: 80
              resources: {}
    - apiVersion: v1
      kind: Service
      metadata:
        labels:
          run: test-nginx
        name: test-nginx
        namespace: default
      spec:
        ports:
        - port: 80
          protocol: TCP
          targetPort: 0
        selector:
          run: test-nginx
  ```
### **To Reproduce**
1. create the work in the hub, wait all of manifest applied in member cluster
2. run below command line to delete AppliedWork
```
kubectl delete AppliedWork test-work
```

### **Expected behavior**
I expect the AppliedWork and other resources in manifest be recreated in member cluster. But they wasn't be recreated.

### **Screenshots**
I saw below error logs.
I0721 19:36:58.253488       1 apply_controller.go:73] "Work apply controller reconcile loop triggered." item="default/test-work-2"
I0721 19:36:58.253736       1 work_status_controller.go:65] "Work Status controller reconcile loop triggered" item="default/test-work-2"
I0721 19:36:58.278963       1 apply_controller.go:149] "resource status update succeeded" Work="default/test-work-2"
1.6584322182790926e+09	DEBUG	events	Normal	{"object": {"kind":"Work","namespace":"default","name":"test-work-2","uid":"6ea81cb3-b9ed-4643-8414-bbfc37a2a6f7","apiVersion":"multicluster.x-k8s.io/v1alpha1","resourceVersion":"165872"}, "reason": "ReconciliationComplete", "message": "manifest apply completed"}
I0721 19:44:36.373905       1 finalize_controller.go:51] "Work finalize controller reconcile loop triggered." item="default/test-work"
E0721 19:44:36.373996       1 finalize_controller.go:76] "resource retrieval failed" err="expected pointer, but got nil" AppliedWork="test-work"
1.6584326763740442e+09	ERROR	controller.work	Reconciler error	{"reconciler group": "multicluster.x-k8s.io", "reconciler kind": "Work", "name": "test-work", "namespace": "default", "error": "expected pointer, but got nil"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
